flybywiresim/website

package-lock.json
package.json
src/about/About.js
src/installation/A32NXInstallInstructions.js
src/utils/constants.js

Fixes the github link in about page to point to new repo.
Changed stable build link to point to the latest github release download, which is a zip with only the A32NX folder inside, and the url will never need to be changed.
Removed the pre release build because it is currently older than the stable version.
Fixed install folder paths and added path for Boxed edition.

Use the release download link instead of master branch and other fixes

---

src/App.css
src/installation/A32NXInstallInstructions.js

This PR redesigns a bit of the install page to give a better text flow, and improve readability both in desktop and mobile versions of the page.
Things that have changed:
- Aligned text to the left, giving a better text flow over a step by step instruction
- Separated titles from paragraphs (Basically separating "Step #" from the description of the step)
- This improves creates a hierarchy between title and descriptions
- This means that the descriptions are not in all-caps anymore, improving readability as well
- Put the warning banner inside a bootstrap alert, so it looks nicer
- Made all columns a `col-lg-8` for consistency
- Made it clear that the installer and manual installations are 2 separate ways of achieving the same thing, by putting them inside `Option 1` and `Option 2` …

A32NX Installation page redesign

---

public/changelog.json

Adds latest changelog info according to https://github.com/flybywiresim/a32nx/releases/tag/v0.4.2

Updates v0.4.2 changelog info

---

src/components/app/Card.tsx
src/components/app/Features.tsx

I changed the color of the text on the titles of the features cards and wrote/added the text that goes in the cards along with the subheading.
BEFORE:
AFTER:

feat: add features text and color change

---

src/components/app/Download.tsx

I added hover states to the buttons on the downloads section.
HOVER:
NO HOVER:

feat: add button hover states

---

src/components/app/Download.tsx

I fixed the capitalization of the words in downloads.
BEFORE: 
AFTER:

fix: downloads grammer fix

---

src/components/app/PartnerSection.tsx

I added hover states to the partner's section.
NO HOVER:
HOVER:
The image will slightly expand.

feat: add hover states to partners

---

src/components/app/Footer.tsx

I added hover underlines on Terms of Service and Privacy Policy.
NO HOVER:
HOVER:

feat: added underlines on the tos and pp

---

src/components/app/Header.tsx

I changed the hover color of the Manual button on the header.
BEFORE:
AFTER:

feat: change manual button hover text color

---

src/components/app/Download.tsx

I removed the indent on the downloads section.
BEFORE:
AFTER:

fix: remove indentation on downloads bullets

---

src/components/app/Footer.tsx

I adjusted the TOS and PP text for larger mobile devices without impacting smaller devices,
BEFORE:
AFTER:

fix: adjusted tos and pp for mobile devices

---

src/components/app/Header.tsx
src/components/app/NavLinks.tsx

I changed the names of the nav links and renamed "Documentation" to "Learn More" as well as removing the link from Learn More and moving it to "Documentation"
BEFORE:
AFTER:

feat: renamed nav links and learn more

---

src/components/utils/NavLinks.tsx

I added functional links to the community dropdown.
BEFORE:
AFTER:

feat: add functional links to dropdown

---

src/components/utils/Error404.tsx

I changed the text on the 404 to something more MSFS related.
BEFORE:
AFTER:

feat: change 404 text

---

src/components/utils/NavBar.tsx

I made the navbar transparent at the top of the header on mobile, on the new video, it is much easier to see on small devices.
BEFORE:
AFTER:

fix: mobile navbar opacity

---

src/App.tsx
src/components/legal/PrivacyPolicy.tsx
src/components/legal/TermsOfService.tsx
src/components/utils/Footer.tsx

This creates dedicated pages for both the terms of service and the privacy policy. This means that we no longer have to force the user to download a pdf to view either of them anymore. Still learning so the code might be really shaky or take some refactoring, but the code still works great on desktop and mobile. Even though this was meant to replace the PDF versions, they are still available for download on their respective pages.
Terms of Service:
Privacy Policy:

feat: add Privacy Policy and Terms of Service pages to replace pdf

---

src/components/home/Installer.tsx

Fixes minor scaling issues when going from a medium screen to a larger one with the installer section. 
Medium:
Large:

fix: minor installer-section alignment issues while scaling

---

src/components/utils/Dropdown.tsx

Community section for NavBar had a gap so a margin has been added to compensate.

fix: navbar margin

---

public/index.html

Sorry, I deleted a line which made the favicon not show on Apple devices. Short and sweet PR to put the line back in and have it point to the favicon location.

fix: put back in line to show favicon on apple devices

---

src/components/utils/NavLinks.tsx

remove `hover:text-gray-200` as there is already `hover:text-blue-light` overwriting it.
No 😏

refactor: remove redundant hover color properties

---

src/components/utils/NavLinks.tsx

Put a donate tab in the community drop-down menu that opens https://opencollective.com/flybywire in a new tab.

refactor: put a donate tab in drop down menu

---

src/components/home/Donate.tsx
src/components/home/Download.tsx
src/components/home/Installer.tsx
src/components/home/headers/A320Header.tsx
src/components/home/headers/A380Header.tsx
src/components/projects/A32NX/Download.tsx
src/components/projects/A32NX/ExtendedFeatures.tsx
src/components/projects/A32NX/Features.tsx
src/components/projects/A32NX/Hero.tsx
src/components/utils/NavBar.tsx
src/index.css
tailwind.config.js

* Correct many styling inconsistencies
* Unify mobile/tablet margins with new `px-page` utility
Before
After
Before
After
Before
After
Before
After
Before
After

fix: correct styling and layout errors

---

tailwind.config.js

* Fixes an issue where tailwind classes used by `react-components` were no longer excluded after enabling tailwind JIT

fix: re-exclude react-components tw classes

---

pages/privacy.tsx
pages/tos.tsx

change "At flybywire simulations" to "At FlyByWire Simulations"

refactor: fix typo in tos and privacy sections

---

components/home/PartnerSection.tsx

Adding a temporary negative top margin to account for the odd temporary sim4flight png we are currently using. 
Before: 
After:

refactor(partners): add -margin to push up temporary sim4flight png

---

components/utils/Footer.tsx

Add the cursor-pointer property to the divs enclosing both the tos and privacy links in the footer to get rid of the unwanted text-selection cursor that showed up before.

fix: add cursor-pointer to remove text-selection cursor

---

styles/iframe.scss
styles/main.scss

Adds CSS classes, one to be used on the containing div of an iframe, and one to be used on the iframe itself. These classes ensure that the iframe will scale responsively and remain within the main blog area.
With: 
Without😒:
Within markdown files, use the classes as such:
```html
<div class="responsive-container">
<iframe 
class="responsive-iframe" 
src="https://www.youtube-nocookie.com/embed/YH0iAGiXkHE" 
title="YouTube video player" frameborder="0" allow="accelerometer; 
autoplay; clipboard-write; encrypted-media; gyroscope; 
picture-in-picture" allowfullscreen>
</iframe>
</div>

style: add css classes to ensure smooth and responsive iframe embeds

---

pages/notams/index.tsx

Make preview images undraggable on NOTAMS main page

refactor: make preview images undraggable on NOTAMS main page

---

pages/notams/[id].tsx

Adds padding to article so that it isn't so close to the header and footer
Before: 
After:

refactor: add padding so the article content isn't so close to header/footer

---

components/home/Donate.tsx
components/home/Installer.tsx
components/home/PartnerSection.tsx
components/utils/Footer.tsx
components/utils/NavBar.tsx
pages/notams/[id].tsx
pages/notams/index.tsx
pages/privacy.tsx
pages/tos.tsx

Fixes N/A
+ All images converted to NextJS image optimization. 
This PR improves the performance of the website by cutting the size of images to only what is necessary and doesn't lose that much quality.
This PR requires either Vercel to host the page or we would require an image loader service to get ```next/image``` to work.

refactor(images): use next image optimization

---

src/components/utils/NavBar.tsx

Adds resize listener so that isOpen is set to false when the user resizes the window past the md breakpoint (768px).

feat: have isOpen set to false when user goes past breakpoint

---

src/posts/a32nx-full-speed-ahead.md

- Added new blog page A32NX: Full Speed Ahead.
Facilitates the server announcement and publishing to relevant social media. 

docs(blog): developer update notam

---

src/components/projects/A32NX/Download.tsx
src/pages/a32nx.tsx

Add conditional rendering to disable the experimental download link.
The link can be disabled by adding the `expOnHold` prop to the `Download` component in `src\pages\a32nx.tsx`
**Before:**
**After:**

feat: add conditional rendering for exp download

---

src/posts/a32nx-flight-model.md

Rapid correction to recently published NOTAM to clearly identify what "A32NX" model is based on and not only recent changes.
Added a corrections clause to the end of the post and additional editors.

fix(blog): post publish corrections to flight model notam

---

src/components/home/A320Header.tsx
src/pages/404.tsx

- moves A32NX video source location from BunnyCDN to Cloudflare R2

chore: move A32NX video to cloudflare

---

src/styles/global.scss

Removes the dots above all map markers, due to leaftet default css inluding a border on the .leaflet-div-icon class.
Class used to place markers (planes) on the map.
Before:
After:

fix: removes dots above map markers

---

src/components/Navigation/Footer.tsx
src/constants/links.ts

Adds press kit link to footer section for quick and visible access to branding policies.

feat: add press kit link to footer

---

src/components/Navigation/Footer.tsx
src/constants/links.ts
src/pages/downloads/index.tsx
src/pages/projects/index.tsx

EFB links changed on footer, and projects index to reflect new URL.
Installer link also fixed on footer to actually do something
Installer link on download updated to CF link

fix: efb and installer links

---

src/components/Navigation/Footer.tsx

Fixes #537
Fixes the issue with the wrong link to the A32NX page.

Fix: Bad link to the A32NX page in the footer
