src/installation/A32NXInstallInstructions.js

The installation instructions don't put anywhere that it replaces the plane, let's do that. :)

Improve install instructions

---

src/installation/A32NXInstallInstructions.js
src/utils/constants.js

This is to add the installer download to the website.

Added the a32nx Installer to Install page

---

.dockerignore
Dockerfile
resources/js/app.js
resources/js/components/ActiveFlights.js
resources/js/components/Contributors.js
resources/views/site/index.blade.php

- Improve caching abilities
- Fix Missing update on active flights
- Add contributors counter

Contributors count

---

app/Http/Controllers/Site/SiteController.php
resources/views/site/documentation.blade.php
resources/views/site/groundschool.blade.php
resources/views/site/resources.blade.php
routes/web.php

The Editing of the Dropdown Items is in a separate pull request

Added Pages for Items under the Pilot Dropdown

---

src/components/app/Download.tsx

I added text to the download section in the download section.
BEFORE:
AFTER:

feat: add text to the download section

---

src/components/app/Card.tsx
src/components/app/Features.tsx

I added custom icons to the features list on the website.
Note: The icons need to be resized in a separate PR.

feat: added icons to features

---

package-lock.json
package.json
src/App.tsx
src/components/app/Footer.tsx

I added a footer to the website.

feat: add footer

---

src/components/app/Header.tsx
src/components/app/NavBar.tsx

I made the FBW logo on the header go back to the home header when clicked.

feat: added anchor to fbw logo on header

---

src/components/app/Download.tsx

I changed the download button colors and hover states.
BEFORE: 
AFTER:

feat: change download button colors

---

src/components/app/Card.tsx

refactor: Change of CardTitle to bold

---

src/components/app/NavBar.tsx

I re-enabled the nav links in the navbar.

feat: re-enable nav links 

---

src/components/app/Download.tsx
src/components/app/Features.tsx
src/components/app/Header.tsx

Fixes #89
I fixed the issue with the download anchor and cleaned up some code.

fix: download anchor and cleanup

---

src/components/app/Download.tsx

I changed the text in the downloads section.
BEFORE:
AFTER:

feat: change download section text

---

public/index.html

Fixes #95 
I edited the HTML metadata for better SEO optimization.

feat: changed website metadata

---

src/components/home/Donate.tsx

Fixes #106 
I fixed the bleeding content in the donation section.
BEFORE:
AFTER:

fix: bleeding content in donate

---

src/App.tsx
src/components/utils/Error404.tsx

Added an Error 404 page that displays to the user every time an unrecognized website URL is entered.
Before:
After:

feat: add error 404 page

---

src/components/utils/Footer.tsx

fix: version number

---

src/components/home/Discord.tsx

I changed the padding on mobile (too squished)
BEFORE:
AFTER:

fix: mobile padding

---

src/components/home/Features.tsx

Change the icons to make more sense.
Before:
After:

refactor: change features section icons

---

src/components/projects/A32NX.tsx

I changed it's to its in Dan's quote. My mistake.

fix: quote grammar

---

src/App.tsx
src/ScrollToTop.tsx

Fixes #128 
I fixed a problem where the page would not scroll to the top when switching pages.

refactor: scroll to top on page change

---

src/App.tsx
src/ScrollToTop.tsx
src/components/utils/Error404.tsx

I added a missing return type.

fix: return type error

---

src/App.tsx
src/components/home/Header.tsx
src/components/utils/Error404.tsx

I made the "download" button functional and renamed it.
I also included a very minor return error.

fix: scroll to installer

---

src/components/projects/ExtendedFeatures.tsx

I made extended features line up with the section below for more continuity.
BEFORE:
AFTER:

refactor: extended features lineup

---

src/components/utils/Error404.tsx
src/components/utils/Footer.tsx

Minor fixes to 404 page and slight refactor.

refactor: 404 page

---

.eslintrc.json
package.json
src/App.tsx
src/components/Button.tsx
src/components/home/Community.tsx
src/components/home/Discord.tsx
src/components/home/Donate.tsx
src/components/home/Header.tsx
src/components/home/Installer.tsx
src/components/home/PartnerSection.tsx
src/components/legal/PrivacyPolicy.tsx
src/components/legal/TermsOfService.tsx
src/components/projects/A32NX/Download.tsx
src/components/projects/A32NX/Features.tsx
src/components/projects/A32NX/Hero.tsx
src/components/utils/Card.tsx
src/components/utils/Dropdown.tsx
src/components/utils/Error404.tsx
src/components/utils/Footer.tsx
src/components/utils/NavBar.tsx
src/components/utils/NavLinks.tsx
src/index.tsx
src/react-app-env.d.ts

* Switch to `@flybywiresim/eslint-config`
* Fix new lint errors

build: switch to fbw eslint config

---

src/components/home/Header.tsx
src/components/utils/Dropdown.tsx
src/components/utils/NavLinks.tsx

refactor: improve nav links

---

package.json
tailwind.config.js

* Enable use of PurgeCSS by updating `react-components` to `0.2.4`

fix: enable PurgeCSS

---

.github/workflows/pr.yml

build: add lint to pr

---

src/components/home/Community.tsx

Fixes N/A
Number now hard set to 1M+

feat: add millions to community counter

---

src/components/utils/NavLinks.tsx

fix: twitter link redirected to facebook

---

components/utils/NavBar.tsx
components/utils/NavLinks.tsx

fix: hamburger

---

README.md

refactor: readme for next.js

---

components/home/Discord.tsx
components/home/Download.tsx
components/home/Installer.tsx
components/projects/A32NX/Download.tsx
components/projects/A32NX/Hero.tsx
components/utils/Dropdown.tsx

Fixes N/A
+ Remove unnecessary text-white

refactor: remove unnecessary classes

---

package-lock.json
package.json

chore: update react components

---

components/projects/A32NX/Download.tsx

fix: update experimental link

---

components/utils/NavLinks.tsx

fix: cursor pointer on NavLink

---

styles/global.scss

Change scrollbar color and border radius to look less out of place. 
Before:
After:

refactor: change scrollbar radius and color

---

package-lock.json
pages/_document.tsx

fix: document initial properties

---

components/utils/ScrollToTopButton.tsx
pages/_app.tsx

Fixes N/A
+ Add new scroll to top button

feat: add scroll to top button

---

README.md

Add **Powered by Vercel** SVG to README

feat: add Powered by Vercel svg into README

---

components/utils/Footer.tsx

fix: vercel link

---

components/home/Donate.tsx
components/home/PartnerSection.tsx
components/home/headers/A320Header.tsx
tailwind.config.js

Fixes N/A
+ Add parallax effect to header hero

feat: hero parallax effect

---

LICENSE

Fixes N/A
+ License switch from MIT to AGPL.

docs(license): MIT to AGPL

---

components/utils/Footer.tsx

Remove version number from footer
Before:
After:

refactor: remove version number from footer

---

src/components/utils/NavBar.tsx

make navbar close when clicking on link and click outside of menu

refactor: make navbar close when clicking on link and click outside of menu

---

src/pages/notams/[id].tsx

change page title to match notams title

feat: dynamically change page title to match notams title

---

src/components/home/Installer.tsx
src/components/home/headers/A320Header.tsx

have handleClick scroll to the element instead of scrolling using a fixed size value.

refactor: scroll to element instead of using hard coded size value

---

src/components/utils/NavLinks.tsx

feat: make home navbar link not show on home page

---

src/components/utils/NavBar.tsx

feat: dynamic hamburger menu

---

src/components/utils/NavLinks.tsx

fixes user not being able to click anywhere on the navlink to follow the link.

fix: user not able to use the entire area of navlink

---

src/pages/a32nx.tsx

refactor: enable experimental

---

package-lock.json
package.json
tailwind.config.js
tsconfig.json

Bump tailwindcss to v3, make necessary config changes, and bump closely related dependencies.

bump: tailwindcss to v3 along with closely related dependencies

---

src/components/home/Community.tsx

Add id="community" to be able to anchor link the homepage's community section

feat: Add id to be able to anchor link the homepage's community section

---

next-env.d.ts
src/components/home/Download.tsx
src/components/projects/A32NX/Download.tsx

Updated download links to bunny cdn links

fix: Updated download links to bunny cdn links

---

src/posts/flypados3.md

As discussed in support ops to provide clarity for aircraft states.

blog: flypados3 correction

---

src/components/projects/A32NX/Download.tsx
src/pages/a32nx.tsx

Supports experimental being removed 
Changed the wording a little bit to be in line with docs and general branding

refactor: put experimental on hold

---

src/components/home/A320Header.tsx
src/components/home/Community.tsx
src/components/home/Donate.tsx
src/components/home/Installer.tsx
src/components/home/PartnerSection.tsx
src/components/projects/A32NX/Download.tsx
src/components/projects/A32NX/ExtendedFeatures.tsx
src/components/projects/A32NX/Features.tsx
src/components/projects/A32NX/Hero.tsx
src/components/utils/Button.tsx
src/components/utils/Card.tsx
src/components/utils/Container.tsx
src/components/utils/Dropdown.tsx
src/components/utils/Footer.tsx
src/components/utils/NavBar.tsx
src/components/utils/NavLinks.tsx
src/components/utils/ScrollToTopButton.tsx
src/pages/404.tsx
src/pages/a32nx.tsx
src/pages/map.tsx
src/pages/notams/[id].tsx
src/pages/notams/index.tsx
src/pages/privacy.tsx
src/pages/tos.tsx

refactor: fix lint

---

src/components/projects/A32NX/Download.tsx

Use new URL as artifact name changed due to compression changes.

fix: download url for dev

---

README.md

fix(readme): support light / dark mode

---

src/posts/a32nx-flight-model.md
src/posts/a380x-full-speed-ahead.md
src/posts/all-the-downloads.md
src/posts/cfms-vnav.md
src/posts/cfms.md
src/posts/development_notam-2021-07-13.md
src/posts/development_notam-2021-08.md
src/posts/development_notam-2021-10.md
src/posts/features-and-projects.md
src/posts/flypados3.md
src/posts/fsweekend-2024.md
src/posts/hydraulics-update-2022.md
src/posts/systems_notam-2022-02.md
src/posts/vdl3.md

Updated all "General Information" section links.
https://docs.flybywiresim.com/fbw-a32nx/support/ -> https://docs.flybywiresim.com/aircraft/support/
https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/ -> https://docs.flybywiresim.com/aircraft/support/known-issues/
https://flybywiresim.com/a32nx/#download -> https://flybywiresim.com/downloads/
Discord: LunakisLeaks

Updated all "General Information" links 

---

src/pages/downloads/index.tsx

fix: A32NX stable download link
